name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: f5633102-f430-4dff-9c4d-1a902990d17b
          tenant-id: 496c6716-d07f-46ce-b75c-d66f5f955766
          client-secret: r0.8Q~Fz6e1pcdEtDwMMa8xBjucxn7zGbevtMbrZ
          subscription-id: 13ea88a3-27fb-4f0f-8e2a-6e1a4ed21f57

      - name: Deploy to Azure SWA
        uses: azure/webapps-deploy@v3
        with:
          app-name: domiclone
          resource-group-name: DOMINO-CLONE
          package: ./dist
